### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by jovial** [mrlesmithjr/ansible-chrony#17]
At present there are no versioned releases on [ansible galaxy](https://galaxy.ansible.com/mrlesmithjr/chrony). I was just wondering if we could make a release so that I can specify a version in my galaxy requirements. Loving the role and thank you for your hard work :)

**Comment by jovial** [comment]
Sorry, just realised there is a release, but for some reason it is not showing or hasn't been imported into galaxy.

**Comment by mrlesmithjr** [comment]
Should be good to go now

**Comment by jovial** [comment]
I can see `v0.1.0` on galaxy - thank you very much :)
